name: GBCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: gbo

    steps:
      - name: Disable SSL verification (temporary)
        run: git config --global http.sslVerify false

      - uses: actions/checkout@v4

      - name: Install zip utility
        run: |
          which zip || sudo apt-get update && sudo apt-get install -y zip

      - name: Generate extension ZIP
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          ZIP_NAME="general-bots-extension-v${VERSION}.zip"

          zip -r "$ZIP_NAME" \
            manifest.json \
            background.js \
            content.js \
            popup.html \
            popup.js \
            popup.css \
            options.html \
            styles.css \
            icons/

          echo "Created: $ZIP_NAME"
          ls -la "$ZIP_NAME"

      - name: Deploy extension ZIP
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          ZIP_NAME="general-bots-extension-v${VERSION}.zip"

          sudo mkdir -p /opt/gbo/releases/botplugin
          sudo cp "$ZIP_NAME" /opt/gbo/releases/botplugin/
          sudo cp "$ZIP_NAME" /opt/gbo/releases/botplugin/general-bots-extension-latest.zip

          echo "Deployed extension to /opt/gbo/releases/botplugin/"
